#LAYERS
# Background
# Layer 1 - background of building
# Layer 2 - interactables and cosmetics
# Layer 3 - collidables with player

#LEGEND
#
# P = Player
# F = Floor
# R = Roof
# C = Cracked wall
# D = Death block
# L = Lava
# S = Stair
# W = Wall
# T = Trap


level_map_1 = [
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBB?XXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                                BBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBB?YXXXXXXXXXXXXXXXXXXXXXXX  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBB?BYXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
'?                  BYXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXX BBB XXX BBB XXX BBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
' YIIIIIIIIIIK&HIIIIIXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             XBX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                      ',
' VXRO123XQXXJ~LXRXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
' VOFX4 5XAXOM^NXFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
' VXCX6 7OTXXJ0GXCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'(                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'BBBBBBBBBBBBBBBBBBB( XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX B XXXXXXX B XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                 XXXXXXXXXX           ',
'BBBBBBBBBBBBBBBBBBBB(  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XBX       XBX                 XXX     XXX     XXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXX       BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXX BBB XXX BBB XXX BBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXX  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXX BBB XXX BBB XXX BBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXX BBB XXX BBB XXX BBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBB( XX                 XX )BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXBBBBBXXXBBBBBXXXBBBBBBBB                                                BBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXX BBBBBBBBBBB',
'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX BBBBBBBBBBB',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                          XXXXXXXX            ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',                                                                                                                                                                                                                                                           
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXX XXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  XXXXXXXXXXXXXXXXXXXXXXXX    ',
'                                                                                                                                                                                                                                                                                                                  [----------------------]    ',
'                                                                                                                                                                                                                                                                                                                                              ']

level_map_2 = [
'                                                                                                                                                                                                                                                                                                                                              ',
'                      _DDDDDDDDDDDDDDDDDDDDDDD_                                                                   ________________________________________________      8______________________________________________________________________________________________                                                                       ',
'                     /                         9                                                                 8                                                9     8                                                                                              9                                                                      ',
'                    /                          |                                                                 8                                                9     8                                                                                              9                                                                      ',
' __________________/                            9                                      DDD     DDD     DDD       8                                                9     8                                                                                              9                                                                      ',
'8                                               |_____________   _____DDDDDDDDDDDDDDDD/   |DDD/   |DDD/   |DDDDDD/                                                |_____/                                                                                              |______________________________________________________________________',
'8                      E           <=>    E                   9 8                                                                              E                                                                                                                                                                                              ',
'8                     <==>              <==>                  9 8                                                    <================>    <=======>   <======>                                                                            <=====>                                                                                            ',
'8     P                       <=>                             |D/                                                                                                                      <====>                                                                <====>                                                                           ',
' ------------------]                                     [-]       [-]                                                                                                      <=====>               <======>                <====>   <====>            <==>                E    E      E     E     E     E E      E     E                       ',
'                    ]                                    9 8       9 8                                                    E             E          E      E                                                    <=====>                                                 [-------------------------------------------------]        [-----------', 
'                     -]   <==>        E                [-   -------   ----------------]   [---]   [---]   [------]   <===========>    <=====>   <=============>   [-----]                                                                                              9                                                 8        9           ',
'                      8>            <===>       [------                               8   9   8   9   8   9      8                                                9     8                                                                                              9                                                 8        9           ',
'                      8                       [-                                      8   9   8   9   8   9      8=>                                            <=9     8                                                                                              9                                                 8        9           ',
'                      8      E  E   E E      <9                                       8   9   8   9   8   9      8        E      E        E     E     E     E     9     8                                                                                              9                                                 8        9           ',
'                       ]UU[---------------]UU[                                         UUU     UUU     UUU        [----------------------------------------------]      8                                                                                              9                                                 8        9           ',
'                                                                                                                                                                        8                                                                                              9                                                 8        9           ',
'                                                                                                                                                                        8                                                                                              9                                                 8        9           ',
'                                                                                                                                                                        8UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU9                                                 8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                         8        9           ',
'                                                                                                                                                                                                                                                                                                                  DDDDDDD/        |DDDDDDD    ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',                                                                                                                                                                                                                                                           
'                                                                                                                                                                                                                                                                                                                 8           S            9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                 8                        9   ',
'                                                                                                                                                                                                                                                                                                                  [----------------------]    ',
'                                                                                                                                                                                                                                                                                                                                              ']

level_map = [level_map_1, level_map_2]

tile_size = 32
screen_width = 1080
screen_height = 19 * tile_size




